server {
    listen 80 default_server;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    recursive_error_pages on;
    error_page 404 /404.html;

    location / {
        try_files $uri $uri/index.html @404;
    }

    location @404 {
        return 404;
    }

    location = /404.html {
        internal;
    }

    location ~ /\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt  {
        access_log off;
        log_not_found off;
    }
}
